version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: quizo-backend
    container_name: quizo-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: quizo-frontend
    container_name: quizo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
